language: go
go:
  - "1.1"
  - tip

services: mongodb

install:
- go get -d -v ./...
- go get -u launchpad.net/gocheck
- go get code.google.com/p/go.tools/cmd/cover
- go get -u github.com/mattn/goveralls

script:
- go install -a -race std
- export PATH=$HOME/gopath/bin:$PATH
- ./check.sh
- goveralls -coverprofile=profile.cov -service=travis-ci
